name: Build and Deploy

on:
  push:
    branches:
      - main  # Cambiá si usás otra rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64 -t ezemarcel/finanzaswp:latest . --push

      - name: Trigger Portainer webhook
        run: |
          curl -X GET https://portainer.francelsoft.com/api/stacks/webhooks/7bb92b56-a812-48ac-ad00-8c1087b01137
